import Head from 'next/head';
import Image from 'next/image';
import { getHomePage } from '../lib/queries';
import { Page } from '../generated/graphql';
import { useQuery } from 'react-query';

interface Props {
    pageData: Array<Page>;
}
export default function Home({ pageData }: Props) {
    const { data } = useQuery('home-page', getHomePage, {
        initialData: pageData,
        notifyOnChangeProps: 'tracked',
    });
    console.log(data);
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>{data && <h1>{data.nodeByUri.title}</h1>}</main>
        </div>
    );
}

export async function getStaticProps({}) {
    const pageData = await getHomePage();
    return {
        props: {
            pageData,
        },
        revalidate: 300,
    };
}
